apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-chetna-ack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chetna-ack 
  name: test-chetna-ack
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-chetna-ack 
